name: Update README

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Concatenate files
      run: |
        sed -i '/<!-- CONTRIBUTORS:START -->/,/<!-- CONTRIBUTORS:END -->/{//!d}' README.md
        echo "<!-- CONTRIBUTORS:START -->" >> README.md
        cat CONTRIBUTORS.md >> README.md
        echo "<!-- CONTRIBUTORS:END -->" >> README.md

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Updated README" || exit 0
        git push

