name: Update Contributors

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Contributors
        run: |
          repo=${{ github.repository }}
          contributors=$(curl -s "https://api.github.com/repos/$repo/contributors" | jq -r '.[].login')
          echo "## Contribuidores" > contributors.md
          for contributor in $contributors; do
            echo "- $contributor" >> contributors.md
          done
          cat contributors.md >> README.md
