name: Update Contributors

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Contributors
        run: |
          repo=${GITHUB_REPOSITORY#*/}
          owner=${GITHUB_REPOSITORY%/*}
          contributors=$(curl -s "https://api.github.com/repos/$owner/$repo/contributors" | jq -r '.[].login')
          echo "## Contributors" > contributors.md
          for contributor in $contributors; do
            echo "- $contributor" >> contributors.md
          done
          sed -i '/<!-- CONTRIBUTORS:START -->/,/<!-- CONTRIBUTORS:END -->/{/<!-- CONTRIBUTORS:START -->/{p;r contributors.md}; /<!-- CONTRIBUTORS:END -->/q}' README.md



